// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wxidhpfvvczsizpmolls.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind4aWRocGZ2dmN6c2l6cG1vbGxzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwODE3NDcsImV4cCI6MjA3MDY1Nzc0N30.XQ9l_VZjwW_HX4hvtGPghe321KX478HzhACYrOIjSG4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});